### ISSUE TITLE
Support for several ticket databases

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#25]
I would like to be able to mention several tickets in the commit message that will be looked up in several databases.

I might be using several Track database, or even have several Jira servers.

This issue was converted from Fogbugz case 9783 (Praqma's internal issue tracker). The case was resolved there as Github issues is now official tracker for PAC.

**Comment by JKrag** [comment]
If we are talking about different issue trackers, or at least something where we can otherwise distinguish between the references via different regex, then this should already be fully supported?

e.g. 

- ABC-13 matches a jira regex  -> look up in jira
- XYZ-25 matches a dirrefent jira regex -> look up in totally different jira server
- #1234 matches a github regex -> look up in github
- REQ1234 matches a requirement regex -> look up in requirement system

@MadsNielsen Do you agree?

**Comment by buep** [comment]
Thanks for pointing that out, according the the feature list in the README we actually already have that support :-)

And our docs specifies also this in more details: https://github.com/Praqma/Praqmatic-Automated-Changelog/blob/master/docs/configuration.md#task-systems
