### ISSUE TITLE
Present and demonstrate PAC 2.0 (case 14551)

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#46]
Call for a pac 2 demonstration in the puclic Josra slack channel. Suggest to create a Praqma meeting invite, which gives you a hangout url you can post on slack.

Meeting should be next week.

I suggest to present and live demo how it works with jira and without at task system. Further how templates works and how to use extra data from the json.

Explain the simple way running it with praqma/pac Docker image. 

Point to more docs related to Windows and our reworked readme file

**Comment by buep** [comment]
What is status? It awaits grooming

**Comment by MadsNielsen** [comment]
I put on the invite for wednesday next week in slack.

**Comment by MadsNielsen** [comment]
I'll follow your suggestions @buep 

I'll have to make a 'better' repository for the demonstration though. One that has a bit more to in that the one we used in development. I'll do a smalli'sh interactive story where i'll add the commits one at a time and show how the 'none' system works, and how we envisioned integration with Jira and a couple of examples. 

There's a bit and tips and tricks i want to show with Liquid as well (using filters). So it's going to be a fairly lengthy demonstration, and i will need a bit of time to create a better scenario. (Which we ofc. will become a script that can be repeated)

**Comment by buep** [comment]
You can off course use prep time but i don't think a day should be spent, then rather do a shorter demo.  

We have the demo scripts, but contact Mike to agree on the scope.

**Comment by MadsNielsen** [comment]
Okay, but im doing a seperate demo for mike monday. I put out the invite in the Josra channel for wedenesday.

**Comment by buep** [comment]
Okay then, if you can reuse as much a possible and we can get a real reuseable demo for many future demos then a day prep is worth it I think.

Remember the demo must be useable by other colleagues so this means scripts and notes and docs enough so you could let me or another do it.

**Comment by buep** [comment]
Since we are in the grooming process again maybee give some bullets on what you will deliver and show.

**Comment by MadsNielsen** [comment]
The demo should cover the following:

1. We should design a repository, with commit messages that makes sense, and better naming than the current 'dev' demo we have. (idRepository...) 
2. We should show how the 'none' system works, in that we can match issue without a task management system
3. We should show an example on how we envision integration with Jira task system, namely what fields that could make sense to include in changelog and how to reference the field in the template.
4. Demo on how to mix and match task systems (multiple). Example would be `none`+ `jira` in the same changelog
5. Some notes on liquid, namely on how to use filters in Liquid templates. (Kinda like built in liquid methods that can manipulate strings... for example: `{{some.var | to_upper}}  `)

Making it a bit nicer, especially since we want to demo it to our Josra members.

**Comment by buep** [comment]
How will you structure the demo scripts etc you need to create?

I suggest for example one collection for both the jira and none.
You will need a script to create the repository, including zipping it etc. Just like the one we have for tests.
Then there have to be a template and configuration file for each demo these fits the repo as well. 

You also have to document the commands to use during the demo, if it is not completely automated.

Maybee you should split this issue? One for jira demo, one for none demo?

**Comment by MadsNielsen** [comment]
I'm going to limit the scope of this demo. I'm not going to spend more than 2 hours prepping the demo for monday and wednesday. Since i'm not really sure on how to do a proper demo. 

I want to automate it in the sense that i have a git repository, where each and every commit is gradual increment of features to show. The you can just reset HEAD to each of those commits and run PAC on the very same repository. It will also demonstrate the suggested workflow with PAC (With the pac_settings.yml project as part of your own project in a repository). 

Let's keep it super simple for now. And go with that.

**Comment by buep** [comment]
Fine, but you still need to explain what I get for the two hours you plan to spend.

It is all about expectation management and settings goals for the work you plan to do so we have clear goals for when you are done.

**Comment by buep** [comment]
Until then we can't really work on it .. right?

**Comment by buep** [comment]
I can see two hours is used ... what did we get for those two hours? Can't really see anything. Are they wasted?

**Comment by MadsNielsen** [comment]
I wrote a manuscript for the demo and put it here: https://github.com/praqma-test/pac-manuscript

Is this something we want to include in PAC itself?

**Comment by buep** [comment]
Add to the prerequisites that you need to be able to run docker containers

**Comment by buep** [comment]
I added a reference to pac-manuscript in PAC - see https://github.com/Praqma/Praqmatic-Automated-Changelog#demo

**Comment by buep** [comment]
if you update pre-requiisties... with docker and bash... then resolve this issue.

**Comment by MadsNielsen** [comment]
Done. Added sthe stuff.

**Comment by buep** [comment]
OK
