### ISSUE TITLE
Passthrough of arbitrary properties to template generator (case 14555)

### ISSUE THREAD

**Issue by JKrag** [Praqma/Praqmatic-Automated-Changelog#48]
It would be nice to be able to send arbitrary properties through to the template generator, like project name, build number, contact person and so on. 

Motivation: For "big" projects, the overhead of hardcoding this in a custom template is negligible, but for companies with many small projects, it might be more preferable to use generic templates and pass in these custom fields from e.g. the build server.

Description fo feature:
I envision enabling (initially) the following two sub-features:

- Allow specifying arbitrary properties in the global section of the settings file:

```
:general:
  date_template: '%Y-%m-%d'
  :strict: false
  :properties:
    version: 1.0
    bla: "dsaf sdf"
    project_name: "My project"
```

- Allow specifying arbitrary properties on the command line with `--properties` taking a JSON map or similar (whatever is easiest to implement):
`pac.rb <other stuff> --properties={ version : "1.0", foo : "bar"  }``

- At a future time this should probably be extended to also support "global" properties from a global .pac-settings file in user home. This would put the behaviour in alignment with most other unix'y tools and e.g. git.

NOTE on precedence: As per usual, local settings file should override any (not yet supported) global stuff, and command line should override both of the above.

It might be a good idea that all the properties get put in a separate "properties" namespace in the tempalte generator to avoid the risk of overwriting internal fields like `task`. This would make them available in the templates as e.g.  `{{properties.title}}`.

Bonus feature wish: It might also be cool to allow injection of all current environment variables under a env namespace. (maybe optional, i.e. only when `--env-inject` is specified. 

The subtasks are as follows

- [x] Allow the use of the `--properties` flag on the command line
- [x] Inject the properties into the Jekyll template
- [x] Specify properties in the settings file 

The first two ones should be relatively simple to implement (30m + 1.5h including simple test)

**Comment by buep** [comment]
I guess this is based on our internal discussion around passing in title to PAC. It is a great description of the feature and some extensions for it.

I consider this a kind of briefing, so this issue is not really workable but we can create smaller and simpler solvable issues from this one.


To this very detailed description I only have one comment: format should be json, investigate if it is easy to pass in on usual command line as above with respect to special chars and escapes

**Comment by MadsNielsen** [comment]
@buep The listed format @JKrag showed is JSON :) - That's what we need to do. Because then we can just do `JSON.parse(properties)` to get our ruby `Hash` we can pass as a local to Liquid.

**Comment by JKrag** [comment]
@buep Why is this issue not workable? Is there something missing? (just trying to learn here). This issue contains a reasonably full description of the feature requested, with exception of those areas where it is open to artistic freedom of the implementer, e.g. I don't care much about the exact format and name-space decisions, so whatever makes it easy to implement is probably good.

@MadsNielsen has already given me an estimate on this task, in the range of a few hours all told. If this estimate holds, It should not really need breaking down into smaller features.

**Comment by buep** [comment]
Agree the feature description is very good and exactly to a degree we like. Rest more or less is implementation details.

But we have three different roles. Developer that need to know exactly what is expected to give good estimates. One that need to pay and just care about one feature is working as expected. 
Then me personally which more or less decide on the done done criterias.

Further I don't think the estimate of couple of hours holds. Does it include documentation update, both user and devs? And test cases? Which ones?
How do you plan to test the feature?

If you don't already have considered these things do you have a plan I don't think the estimate will hold.

I want to minimize the risk to overrun estimate and half done implementations. 
So suggest to break down the feature in the three parts already described.

Start with the part about support for configuration properties in settings file. Answer each question above with a colleague or two and come with an estimate and some details that answers the part about docs, testing etc.

**Comment by buep** [comment]
Since I requested this issues resolved, not it is started though we didn't groom it properly first @MadsNielsen and I had a talk about what should be included in the resolution:

* implement feature to also specify properties in configuration file
* write more and better tests, we agreed on the following tests:
 * invalid json is handles properly, by catching an exception and showing the problem to the user
 * test that shows properties passed in work in the template
 * test that shows properties from config file works in the template
 * test that shows properties takes precedence over properties from config file
_current test more or less on verifies properties are parsed properly after input - we want to write the tests in a way that ensures that the output generated contain the properties if used in the template. This means we need to make a test where we as part of the test genereate a config file, a template etc. and check that the output from the report modules is as expected. The generate method needs to be refactores to do this I was told  - but that is fine. We don't have to verify the writing of the file._
* exception handling - the user must get a very well formulated error message pointing out what went wrong, and as extra information we can show the original stack trace. For example if the json can not be parsed, I want to be told json parsing failed, and pointet to the line where there is a problem
* documentation on this new properties feature must be written.... sell the feature to the user, explain why it is cool, and explain how to use it. Explain precedence and so forth.

**Comment by MadsNielsen** [comment]
I've added my suggested implemention on a branch: https://github.com/Praqma/Praqmatic-Automated-Changelog/tree/workon/48-part-2/docs

I'd appreciate review and comments.

**Comment by buep** [comment]
Do you think everything is done? is that what I should review?

**Comment by buep** [comment]
General comments:

* add method descriptions to your tests... especially the precedence test could be a bit better explained. the name of the test do not say yo are testing precedence.  

I also added comments to your two commits... next time if you ask to review, please give me one commit with the combined change.... would be so much easier.

Regarding documentation, please proof-read it a bit. Since the explanation to for properties both regards template and configuration, both placed should be updated with information on how to use.
Further I'm missing the background for why this feature is cool.

So either improve both template and configuration documentaion, or write a new section in a markdown file where you explain everything about properties and link to it from configuration and template docs and keep those simple.

**Comment by buep** [comment]
Okay, just checked. Seems okay now :-)

Good catch with the test for the partial override.

**Comment by MadsNielsen** [comment]
Alright then. If you're ok with it, then we should go ahead and push a copy of the branch https://github.com/Praqma/Praqmatic-Automated-Changelog/tree/workon/48-part-3 to a ready branch.

**Comment by buep** [comment]
yep, please deliver it and get it released

I will then announce the new feature
