### ISSUE TITLE
Github support?

### ISSUE THREAD

**Issue by buep** [Praqma/Praqmatic-Automated-Changelog#8]
If it uses json, and return json data it should be simple to support together with Jira as it is more or less the same design.

**Comment by MadsNielsen** [comment]
https://developer.github.com/v3/

**Comment by MadsNielsen** [comment]
I think we can get far using one day of work for this.

**Comment by JKrag** [comment]
I made this work a few weeks ago as a POC in a plane + hotel room. I have currently pushed an experimental/github_support branch just for sharing how I made it work.

In short, it is workable out of the box with the JIRA "plugin" with the needed config changes to the default_settings.yml file. Initially I made it work by disabling the basic_auth in `lib/decorators.rb:21`as I was testing against a public repo anyway (PAC obviously). 

I also had to add some better exception handling in order to debug along the way.

Yesterday I made it work with the unmodified basic_auth by providing a access token I had generated on GitHub, but I haven't pushed this version for obvious reasons, as it has to have the PW hard-coded in the settings file.

I have a few thoughts about different directions we could take this with regards to architecture, and would be happy to brainstorm/discuss, preferably in person.

Very shortly, I am thinking of too main options:

* Rename the exisitng JIRA support into "json-rest" or something, and just document how to use it with JIRA.
* Keep "jira", add "github" and others, as well as a "generic json rest" option, and refactor to extract the 95% code that is reusable.

**Comment by buep** [comment]
Your experimental branch is: https://github.com/Praqma/Praqmatic-Automated-Changelog/tree/experimental/github_support

I prefer your first option with "json-rest" instead of jira/github so we maintain one generic for all the json-rest systems. But I'm open for the discussion.

We can take the discussion when we prioritize the work - that is decide on how to finance it.

**Comment by buep** [comment]
Closing - only thing that remains are the rename mentioned in #69 and minor clean-up
