### ISSUE TITLE
Remove never-used function..like --from-date

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/Praqmatic-Automated-Changelog#90]
We have the ability to look up commits based on date, nobody uses this, it's not easy to do and we have resolution up to `days` not seconds etc.

Involves maintenance and should be removed for 3.0.

**Comment by buep** [comment]
Let's prioritize to remove this since we have introduced tree-ish references. 

The code for date parsing is also a bit complex, so it makes the code simpler if we only support tree-ish.

Changes must include:

* test
* code clean-up
* release of version 3.0, breaking backwards compatibility and explaining this properly
* cleaning up documentation, and command-line help

**Comment by buep** [comment]
Seems like good thorough work... only thing I'm missing is a simple upgrade guide in the README when switching to version 3.x ... I need to update my config file? Can you create a new issue for fixing this if you agree?

**Comment by MichaelMadsen** [comment]
I didn't originally think about it, because there aren't any breaking changes in the config file. You can still keep the date-format in your old config files, if just won't affect anything, and the documentation no longer mentions it so new users won't have it in there.
But I do agree that it makes sense to document this. I'll set up an issue.

**Comment by buep** [comment]
It is great things doesn't break! But worth mentioning old users settings are now ignored :-)
